/* 
 * Copyright (C) 2019 Karim BOUTAMINE <boutaminekarim06 at gmail.com>
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */
package graphicInterfaces;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import static misc.Params.*;
import java.awt.Component;
import java.io.File;
import javax.swing.JFileChooser;
import json.CreateJson;

/**
 *
 * @author Karim BOUTAMINE <boutaminekarim06@gmail.com>
 */
public class Launcher extends javax.swing.JFrame {
    
    /**
     * Creates new form Main
     */
    public Launcher() {
        
        //Init interface components
        initComponents();
        //Init MAIN_* Params
        initParams();
        //Add Listeners to components
        initListeners();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFrame1 = new javax.swing.JFrame();
        jColorChooser1 = new javax.swing.JColorChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jComboBox_variante = new javax.swing.JComboBox();
        jButton_okVariante = new javax.swing.JButton();
        jCheckBox_grid = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_tailleCell = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_shape = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton_color = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_boundaries = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_neighbourhood = new javax.swing.JComboBox();
        jPanel_classes = new javax.swing.JPanel();
        jLabel_classes = new javax.swing.JLabel();
        jTextField_classes = new javax.swing.JTextField();
        jButton_okClasses = new javax.swing.JButton();
        jCheckBox_randColors = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jPanel_colors = new javax.swing.JPanel();
        jButton_color1 = new javax.swing.JButton();
        jButton_color2 = new javax.swing.JButton();
        jButton_color3 = new javax.swing.JButton();
        jButton_color4 = new javax.swing.JButton();
        jButton_color5 = new javax.swing.JButton();
        jButton_color6 = new javax.swing.JButton();
        jButton_color7 = new javax.swing.JButton();
        jButton_color8 = new javax.swing.JButton();
        jPanel_dataLoader = new javax.swing.JPanel();
        jButton_selectData = new javax.swing.JButton();
        jRadioButton_singleValue = new javax.swing.JRadioButton();
        jRadioButton_1xmValues = new javax.swing.JRadioButton();
        jRadioButton_nxmValues = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem_createData = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 56, Short.MAX_VALUE)
                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 57, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automate");
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(1000, 1000));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jComboBox_variante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LifeGame", "DiffusionGathering", "DiffusionClassification", "Turmites", "InfluenceClassification", "InfluenceRepulsion", "Test" }));
        jComboBox_variante.setSelectedIndex(6);
        jComboBox_variante.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_variante, gridBagConstraints);

        jButton_okVariante.setText("OK");
        jButton_okVariante.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton_okVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okVarianteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jButton_okVariante, gridBagConstraints);

        jCheckBox_grid.setText("Grid");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jCheckBox_grid, gridBagConstraints);

        jLabel1.setText("Cell dimention:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jComboBox_tailleCell.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "5", "10", "15", "20", "240", "120" }));
        jComboBox_tailleCell.setSelectedIndex(2);
        jComboBox_tailleCell.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_tailleCell, gridBagConstraints);

        jLabel5.setText("Shape:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jComboBox_shape.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oval", "Square" }));
        jComboBox_shape.setSelectedIndex(1);
        jComboBox_shape.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_shape, gridBagConstraints);

        jLabel4.setText("Agents' color:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        jButton_color.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color.setPreferredSize(new java.awt.Dimension(22, 22));
        jButton_color.setIcon(new ImageIcon(getColorIcon(Color.GRAY)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jButton_color, gridBagConstraints);

        jLabel9.setText("Boundaries:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        jComboBox_boundaries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toric", "Free" }));
        jComboBox_boundaries.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_boundaries, gridBagConstraints);

        jLabel10.setText("Neighbourhood:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel10, gridBagConstraints);

        jComboBox_neighbourhood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moore8", "Von Newman" }));
        jComboBox_neighbourhood.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_neighbourhood, gridBagConstraints);

        this.jPanel_classes.setVisible(false);
        jPanel_classes.setLayout(new java.awt.GridBagLayout());

        jLabel_classes.setText("Classes:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel_classes.add(jLabel_classes, gridBagConstraints);

        jTextField_classes.setText("3");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel_classes.add(jTextField_classes, gridBagConstraints);

        jButton_okClasses.setText("OK");
        jButton_okClasses.setBorder(null);
        jButton_okClasses.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_okClasses.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_okClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okClassesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel_classes.add(jButton_okClasses, gridBagConstraints);

        jCheckBox_randColors.setText("Random Colors");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel_classes.add(jCheckBox_randColors, gridBagConstraints);

        jLabel2.setText("Agent's colors:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.4;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel_classes.add(jLabel2, gridBagConstraints);

        jPanel_colors.setLayout(new java.awt.GridLayout(1, 0));

        jButton_color1.setText("1");
        jButton_color1.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color1.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton_color1.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton_color1.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_color1.setIcon(new ImageIcon(getColorIcon(Color.GREEN)));
        jPanel_colors.add(jButton_color1);

        jButton_color2.setText("2");
        jButton_color2.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color2.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton_color2.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton_color2.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_color2.setIcon(new ImageIcon(getColorIcon(Color.ORANGE)));
        jPanel_colors.add(jButton_color2);

        jButton_color3.setText("3");
        jButton_color3.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color3.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton_color3.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton_color3.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_color3.setIcon(new ImageIcon(getColorIcon(Color.MAGENTA)));
        jPanel_colors.add(jButton_color3);

        jButton_color4.setText("4");
        jButton_color4.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color4.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton_color4.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton_color4.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_color4.setIcon(new ImageIcon(getColorIcon(Color.PINK)));
        jPanel_colors.add(jButton_color4);

        jButton_color5.setText("5");
        jButton_color5.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color5.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton_color5.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton_color5.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_color5.setIcon(new ImageIcon(getColorIcon(Color.YELLOW)));
        jPanel_colors.add(jButton_color5);

        jButton_color6.setText("6");
        jButton_color6.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color6.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton_color6.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton_color6.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_color6.setIcon(new ImageIcon(getColorIcon(Color.RED)));
        jPanel_colors.add(jButton_color6);

        jButton_color7.setText("7");
        jButton_color7.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color7.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton_color7.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton_color7.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_color7.setIcon(new ImageIcon(getColorIcon(Color.CYAN)));
        jPanel_colors.add(jButton_color7);

        jButton_color8.setText("8");
        jButton_color8.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color8.setMaximumSize(new java.awt.Dimension(30, 30));
        jButton_color8.setMinimumSize(new java.awt.Dimension(30, 30));
        jButton_color8.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_color8.setIcon(new ImageIcon(getColorIcon(Color.GRAY)));
        jPanel_colors.add(jButton_color8);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.8;
        gridBagConstraints.weighty = 0.1;
        jPanel_classes.add(jPanel_colors, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jPanel_classes, gridBagConstraints);

        jPanel_dataLoader.setLayout(new java.awt.GridBagLayout());

        jButton_selectData.setText("Load Data");
        jButton_selectData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_selectDataActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel_dataLoader.add(jButton_selectData, gridBagConstraints);

        buttonGroup2.add(jRadioButton_singleValue);
        jRadioButton_singleValue.setText("Single value");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel_dataLoader.add(jRadioButton_singleValue, gridBagConstraints);

        buttonGroup2.add(jRadioButton_1xmValues);
        jRadioButton_1xmValues.setText("[1xm] Values");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel_dataLoader.add(jRadioButton_1xmValues, gridBagConstraints);

        buttonGroup2.add(jRadioButton_nxmValues);
        jRadioButton_nxmValues.setText("[nxm] Values");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        jPanel_dataLoader.add(jRadioButton_nxmValues, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jPanel_dataLoader, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel2, gridBagConstraints);

        jMenu1.setText("File");

        jMenuItem_createData.setText("Create dataset");
        jMenuItem_createData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_createDataActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem_createData);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_okVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okVarianteActionPerformed
        this.runSimulation();
    }//GEN-LAST:event_jButton_okVarianteActionPerformed

    private void jButton_okClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okClassesActionPerformed
        MAIN_NB_CLASSES = Integer.parseInt(jTextField_classes.getText());
    }//GEN-LAST:event_jButton_okClassesActionPerformed

    private void jButton_selectDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_selectDataActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        int returnValue = fileChooser.showOpenDialog(null);
        if (returnValue == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            System.out.println(selectedFile);
//            java.awt.Desktop.getDesktop().open(selectedFile);//<-- here
        }
    }//GEN-LAST:event_jButton_selectDataActionPerformed

    private void jMenuItem_createDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_createDataActionPerformed
        DatasetCreator dtc = new DatasetCreator();
        dtc.setVisible(true);
    }//GEN-LAST:event_jMenuItem_createDataActionPerformed
    
    private void initParams(){
        
        MAIN_CELL_LENGTH = Integer.valueOf(this.jComboBox_tailleCell.getSelectedItem().toString());
        MAIN_SHAPE = this.jComboBox_shape.getSelectedItem().toString();
        MAIN_COLOR_AGENT1 = Color.gray;
        MAIN_BOUNDARY_LENGTH = 0;
        MAIN_RAND_COLORS = false;
        MAIN_BOUNDARIES = this.jComboBox_boundaries.getSelectedItem().toString();
        MAIN_NB_CLASSES = Integer.parseInt(this.jTextField_classes.getText());
        MAIN_GRID = false;
        MAIN_NEIGHBOURHOOD = this.jComboBox_neighbourhood.getSelectedItem().toString();
        RAND = new Random();
        switchVariante(this.jComboBox_variante.getSelectedItem().toString());
        
        MAIN_COLORS_ARRAY = new Color[8];
        MAIN_COLORS_ARRAY[0] = Color.GREEN;
        MAIN_COLORS_ARRAY[1] = Color.ORANGE;
        MAIN_COLORS_ARRAY[2] = Color.MAGENTA;
        MAIN_COLORS_ARRAY[3] = Color.PINK;
        MAIN_COLORS_ARRAY[4] = Color.YELLOW;
        MAIN_COLORS_ARRAY[5] = Color.RED;
        MAIN_COLORS_ARRAY[6] = Color.CYAN;
        MAIN_COLORS_ARRAY[7] = Color.GRAY;
    }
    
    private void initListeners(){
        
        //When cell dimention is changed
        this.jComboBox_tailleCell.addActionListener((ActionEvent e) -> {
            MAIN_CELL_LENGTH = Integer.parseInt(jComboBox_tailleCell.getSelectedItem().toString());
        });
        
        //when shape is changed
        this.jComboBox_shape.addActionListener((ActionEvent e) -> {
            MAIN_SHAPE = jComboBox_shape.getSelectedItem().toString();
        });
        
        //Color chooser to change color
        this.jButton_color.addActionListener((ActionEvent arg0) -> {
            Color c = JColorChooser.showDialog(null, "Choose a color", Color.GRAY);
            if (c!=null) {
                MAIN_COLOR_AGENT1 = c;
                ImageIcon imgIcn = new ImageIcon(getColorIcon(MAIN_COLOR_AGENT1));
                jButton_color.setIcon(imgIcn);
                jButton_color.repaint();
            }
        });
        
        //Init all color buttons with color choosers
        for(Component c : jPanel_colors.getComponents()){
            ((JButton)c).addActionListener((ActionEvent arg0) -> {
                
                int index = Integer.parseInt(((JButton)c).getText()) - 1;
                
                Color clr = JColorChooser.showDialog(null, "Choose a color", MAIN_COLORS_ARRAY[index]);
                if (clr!=null) {
                    MAIN_COLORS_ARRAY[index] = clr;
                    ((JButton)c).setIcon(new ImageIcon(getColorIcon(MAIN_COLORS_ARRAY[index])));
                    c.repaint();
                }
            });
        }
        //When boundaries are set or removed
        this.jComboBox_boundaries.addActionListener((ActionEvent e) -> {
            MAIN_BOUNDARIES = jComboBox_boundaries.getSelectedItem().toString();
            System.out.println("NEED TO BE IMPLEMENTED");
            if(MAIN_BOUNDARIES.equals("Free")) MAIN_BOUNDARY_LENGTH = 1;
            else MAIN_BOUNDARY_LENGTH = 0;
        });
        
        //When Grid is checked
        this.jCheckBox_grid.addItemListener((ItemEvent e) -> {
            MAIN_GRID = e.getStateChange() == ItemEvent.SELECTED;
        });
        
        //When randColors is checked
        this.jCheckBox_randColors.addItemListener((ItemEvent e) -> {
            MAIN_RAND_COLORS = e.getStateChange() == ItemEvent.SELECTED;
            for(Component c : jPanel_colors.getComponents()){
                c.setEnabled(!MAIN_RAND_COLORS);
            }
        });
        
        //When boundaries are set or removed
        this.jComboBox_variante.addActionListener((ActionEvent e) -> {
            
            switchVariante(this.jComboBox_variante.getSelectedItem().toString());
            
            boolean colorPanelAdditonal= 
                    (VARIANTE == Variante.DIFFUSION_CLASSIFICATION 
                    || VARIANTE == Variante.INFLUENCE_CLASSIFICATION
                    || VARIANTE == Variante.INFLUENCE_REPULSION);
            boolean dataLoader=  VARIANTE == Variante.TEST;
            
            jPanel_classes.setVisible(colorPanelAdditonal);
            jPanel_dataLoader.setVisible(dataLoader);
            
        });
    }
    
    private void switchVariante(String str){
        
        switch(str){
            case "DiffusionClassification":
                VARIANTE = Variante.DIFFUSION_CLASSIFICATION;
                break;
            case "DiffusionGathering":
                VARIANTE = Variante.DIFFUSION_GATHERING;
                break;
            case "LifeGame":
                VARIANTE = Variante.LIFE;
                break;
            case "Turmites":
                VARIANTE = Variante.TURMITES;
                break;
            case "InfluenceClassification":
                VARIANTE = Variante.INFLUENCE_CLASSIFICATION;
                break;
            case "InfluenceRepulsion":
                VARIANTE = Variante.INFLUENCE_REPULSION;
                break;
            case "Test":
                VARIANTE = Variante.TEST;
                break;
            default: 
                VARIANTE = Variante.DEFAULT;
                break;
        }
    }
    
    private BufferedImage getColorIcon(Color c){
        BufferedImage colorSample = new BufferedImage(16,16,BufferedImage.TYPE_INT_RGB);
        Graphics2D g = colorSample.createGraphics();
        
        g.setColor(c);
        g.fillRect(0, 0, colorSample.getWidth(), colorSample.getHeight());
        g.dispose();
        
        return colorSample;
    }
   
    /**
     *
     */
    public void runSimulation(){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SimulatorInterface(VARIANTE).setVisible(true);
        });
    }
    
//<editor-fold defaultstate="collapsed" desc="Var Declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton_color;
    private javax.swing.JButton jButton_color1;
    private javax.swing.JButton jButton_color2;
    private javax.swing.JButton jButton_color3;
    private javax.swing.JButton jButton_color4;
    private javax.swing.JButton jButton_color5;
    private javax.swing.JButton jButton_color6;
    private javax.swing.JButton jButton_color7;
    private javax.swing.JButton jButton_color8;
    private javax.swing.JButton jButton_okClasses;
    private javax.swing.JButton jButton_okVariante;
    private javax.swing.JButton jButton_selectData;
    private javax.swing.JCheckBox jCheckBox_grid;
    private javax.swing.JCheckBox jCheckBox_randColors;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox jComboBox_boundaries;
    private javax.swing.JComboBox jComboBox_neighbourhood;
    private javax.swing.JComboBox jComboBox_shape;
    private javax.swing.JComboBox jComboBox_tailleCell;
    private javax.swing.JComboBox jComboBox_variante;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_classes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem_createData;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel_classes;
    private javax.swing.JPanel jPanel_colors;
    private javax.swing.JPanel jPanel_dataLoader;
    private javax.swing.JRadioButton jRadioButton_1xmValues;
    private javax.swing.JRadioButton jRadioButton_nxmValues;
    private javax.swing.JRadioButton jRadioButton_singleValue;
    private javax.swing.JTextField jTextField_classes;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
    
}
