/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package _GUInterfaces;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.event.ActionEvent;
import java.awt.event.ItemEvent;
import java.awt.image.BufferedImage;
import java.util.HashMap;
import java.util.Random;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import _diverse.Params;
import static _diverse.Params.*;

/**
 *
 * @author Karim
 */
public class Launcher extends javax.swing.JFrame {

//    Automaton ac;
    
    /**
     * Creates new form Main
     */
    public Launcher() {
        initComponents();
        initParams();
        initListeners();
    }
    
//<editor-fold defaultstate="collapsed" desc="Setters & Getters">
    
    //Setters and Getters
    
    /** ***********************************************************************/
    /* ************** GETTERS
    /** ***********************************************************************/
    //JComboboxes
    public JComboBox getjComboBox_shape() {
        return jComboBox_shape;
    }

    public JComboBox getjComboBox_tailleCell() {
        return jComboBox_tailleCell;
    }

    public JComboBox getjComboBox_boundaries() {
        return jComboBox_boundaries;
    }

    public JComboBox getjComboBox_variante() {
        return jComboBox_variante;
    }
    
    //JTextFields

    public JTextField getjTextField_classes() {
        return jTextField_classes;
    }
    
    //JButtons

    public JButton getjButton_color() {
        return jButton_color;
    }
    
    //JCheckBoxes

    public JCheckBox getjCheckBox_grid() {
        return jCheckBox_grid;
    }

    
    /** ***********************************************************************/
    /* ************** SETTERS
    /** ***********************************************************************/
    
    //JButtons

    public void setjButton_color(ImageIcon imgIcn) {
        this.jButton_color.setIcon(imgIcn);
    }
    
//</editor-fold>
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jFrame1 = new javax.swing.JFrame();
        jColorChooser1 = new javax.swing.JColorChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        jComboBox_variante = new javax.swing.JComboBox();
        jButton_okVariante = new javax.swing.JButton();
        jCheckBox_grid = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jComboBox_tailleCell = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jComboBox_shape = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jButton_color = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_boundaries = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox_neighbourhood = new javax.swing.JComboBox();
        jLabel_classes = new javax.swing.JLabel();
        jTextField_classes = new javax.swing.JTextField();
        jButton_okClasses = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 698, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 41, Short.MAX_VALUE)
                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 42, Short.MAX_VALUE)))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 442, Short.MAX_VALUE)
            .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jFrame1Layout.createSequentialGroup()
                    .addGap(0, 56, Short.MAX_VALUE)
                    .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 57, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Automate");
        setMinimumSize(new java.awt.Dimension(300, 300));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel2.setMaximumSize(new java.awt.Dimension(500, 500));
        jPanel2.setMinimumSize(new java.awt.Dimension(300, 300));
        jPanel2.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel2.setLayout(new java.awt.GridBagLayout());

        jComboBox_variante.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "LifeGame", "DiffusionGathering", "DiffusionClassification", "Turmites", "InfluenceClassification", "InfluenceRepulsion" }));
        jComboBox_variante.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_variante, gridBagConstraints);

        jButton_okVariante.setText("OK");
        jButton_okVariante.setPreferredSize(new java.awt.Dimension(50, 30));
        jButton_okVariante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okVarianteActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jButton_okVariante, gridBagConstraints);

        jCheckBox_grid.setText("Grid");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.3;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jCheckBox_grid, gridBagConstraints);

        jLabel1.setText("Cell dimention:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel1, gridBagConstraints);

        jComboBox_tailleCell.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "3", "5", "10", "15", "20", "240", "120" }));
        jComboBox_tailleCell.setSelectedIndex(2);
        jComboBox_tailleCell.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_tailleCell, gridBagConstraints);

        jLabel5.setText("Shape:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel5, gridBagConstraints);

        jComboBox_shape.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Oval", "Square" }));
        jComboBox_shape.setSelectedIndex(1);
        jComboBox_shape.setPreferredSize(new java.awt.Dimension(60, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_shape, gridBagConstraints);

        jLabel4.setText("Agents' color:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel4, gridBagConstraints);

        jButton_color.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_color.setPreferredSize(new java.awt.Dimension(22, 22));
        jButton_color.setIcon(new ImageIcon(getColorIcon(Color.GRAY)));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jButton_color, gridBagConstraints);

        jLabel9.setText("Boundaries:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel9, gridBagConstraints);

        jComboBox_boundaries.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Toric", "Free" }));
        jComboBox_boundaries.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_boundaries, gridBagConstraints);

        jLabel10.setText("Neighbourhood:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel10, gridBagConstraints);

        jComboBox_neighbourhood.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moore8", "Von Newman" }));
        jComboBox_neighbourhood.setPreferredSize(new java.awt.Dimension(50, 30));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.2;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jComboBox_neighbourhood, gridBagConstraints);

        jLabel_classes.setText("Classes:");
        jLabel_classes.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jLabel_classes, gridBagConstraints);

        jTextField_classes.setText("3");
        jTextField_classes.setVisible(false);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jTextField_classes, gridBagConstraints);

        jButton_okClasses.setText("OK");
        jButton_okClasses.setBorder(null);
        jButton_okClasses.setMargin(new java.awt.Insets(2, 2, 2, 2));
        jButton_okClasses.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton_okClasses.setVisible(false);
        jButton_okClasses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_okClassesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 5, 0);
        jPanel2.add(jButton_okClasses, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.weighty = 0.1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jPanel2, gridBagConstraints);

        jMenu1.setText("File");

        jMenuItem1.setText("Nouveau Jeu de la vie");
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Nouvea Jeu de la guerre");
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_okVarianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okVarianteActionPerformed
        this.runSimulation();
    }//GEN-LAST:event_jButton_okVarianteActionPerformed

    private void jButton_okClassesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_okClassesActionPerformed
        MAIN_NB_CLASSES = Integer.parseInt(jTextField_classes.getText());
    }//GEN-LAST:event_jButton_okClassesActionPerformed
    
    private void initParams(){
        
        MAIN_CELL_DIM = Integer.valueOf(this.getjComboBox_tailleCell().getSelectedItem().toString());
        MAIN_SHAPE = this.getjComboBox_shape().getSelectedItem().toString();
        MAIN_COLOR_AGENT1 = Color.gray;
//        MAIN_WALL = 0;
        MAIN_BOUNDARIES = this.getjComboBox_boundaries().getSelectedItem().toString();
        MAIN_NB_CLASSES = Integer.parseInt(this.getjTextField_classes().getText());
        MAIN_GRID = false;
        RAND = new Random();
        switchVariante(this.getjComboBox_variante().getSelectedItem().toString());
    }
    
    private void initListeners(){
        
        //When cell dimention is changed
        this.getjComboBox_tailleCell().addActionListener((ActionEvent e) -> {
            MAIN_CELL_DIM = Integer.parseInt(getjComboBox_tailleCell().getSelectedItem().toString());
        });
        
        //when shape is changed
        this.getjComboBox_shape().addActionListener((ActionEvent e) -> {
            MAIN_SHAPE = getjComboBox_shape().getSelectedItem().toString();
        });
        
        //Color chooser to change color
        this.getjButton_color().addActionListener((ActionEvent arg0) -> {
            Color c = JColorChooser.showDialog(null, "Choose a color", Color.GRAY);
            if (c!=null) {
                MAIN_COLOR_AGENT1 = c;
                setjButton_color(new ImageIcon(getColorIcon(MAIN_COLOR_AGENT1)));
                getjButton_color().repaint();
            }
        });
        
        //When boundaries are set or removed
        this.getjComboBox_boundaries().addActionListener((ActionEvent e) -> {
            MAIN_BOUNDARIES = getjComboBox_boundaries().getSelectedItem().toString();
            System.out.println("NEED TO BE IMPLEMENTED");
//            if(MAIN_BOUNDARIES.equals("Free")) MAIN_WALL = 1;
//            else MAIN_WALL = 0;
        });
        
        //When Grid is checked
        this.getjCheckBox_grid().addItemListener((ItemEvent e) -> {
            MAIN_GRID = e.getStateChange() == ItemEvent.SELECTED;
        });
        
        //When boundaries are set or removed
        this.getjComboBox_variante().addActionListener((ActionEvent e) -> {
            
            switchVariante(this.getjComboBox_variante().getSelectedItem().toString());
            
            if(VARIANTE == Variante.DIFFUSION_CLASSIFICATION 
                    || VARIANTE == Variante.INFLUENCE_CLASSIFICATION
                    || VARIANTE == Variante.INFLUENCE_REPULSION) {
                jLabel_classes.setVisible(true);
                jTextField_classes.setVisible(true);
                jButton_okClasses.setVisible(true);
            }
            else {
                jLabel_classes.setVisible(false);
                jTextField_classes.setVisible(false);
                jButton_okClasses.setVisible(false);
            }
        });
    }
    
    private void switchVariante(String str){
        
        switch(str){
            case "DiffusionClassification":
                VARIANTE = Params.Variante.DIFFUSION_CLASSIFICATION;
                break;
            case "DiffusionGathering":
                VARIANTE = Params.Variante.DIFFUSION_GATHERING;
                break;
            case "LifeGame":
                VARIANTE = Params.Variante.LIFE;
                System.out.println("yeeeeeep!");
                break;
            case "Turmites":
                VARIANTE = Params.Variante.TURMITES;
                break;
            case "InfluenceClassification":
                VARIANTE = Params.Variante.INFLUENCE_CLASSIFICATION;
                break;
            case "InfluenceRepulsion":
                VARIANTE = Params.Variante.INFLUENCE_REPULSION;
                break;
            default: 
                VARIANTE = Params.Variante.DEFAULT;
                break;
        }
    }
    
    private BufferedImage getColorIcon(Color c){
        BufferedImage colorSample = new BufferedImage(16,16,BufferedImage.TYPE_INT_RGB);
        Graphics2D g = colorSample.createGraphics();
        
        g.setColor(c);
        g.fillRect(0, 0, colorSample.getWidth(), colorSample.getHeight());
        g.dispose();
        
        return colorSample;
    }
   
    public void runSimulation(){
         /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SimulatorInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new SimulatorInterface(VARIANTE).setVisible(true);
        });
    }
    
//<editor-fold defaultstate="collapsed" desc="Var Declaration">
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton_color;
    private javax.swing.JButton jButton_okClasses;
    private javax.swing.JButton jButton_okVariante;
    private javax.swing.JCheckBox jCheckBox_grid;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JComboBox jComboBox_boundaries;
    private javax.swing.JComboBox jComboBox_neighbourhood;
    private javax.swing.JComboBox jComboBox_shape;
    private javax.swing.JComboBox jComboBox_tailleCell;
    private javax.swing.JComboBox jComboBox_variante;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_classes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField_classes;
    // End of variables declaration//GEN-END:variables
//</editor-fold>
    
}
